# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19f187a09c208b3536efda2ff1b4dd17f14f48de49e5fea2ef46fcf9bccd5589284d7db342603a9f56d028833789338c55a4eb525ba9af658aeb82972f1a60ea

test:
  secret_key_base: 33951498e0c804437f83a1ae5b63788afc4c01af1fd042a0117b80888606e3aae08634b6ac5417a9f6c8487135353e8194dac69bc3a7151abaf9d29a277e46a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
